#!/usr/bin/env bash
# dev-skills harness installer (non-interactive).
# No language auto-detection by design: pass --langs explicitly, or --minimal
# to install only the mechanical rails and decide languages later via /yds-setup.
set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATES="$HARNESS_ROOT/templates"

usage() {
  cat <<'EOF'
Usage:
  setup.sh (--langs go,python,typescript,javascript | --minimal) [options]

Required (one of):
  --langs LIST      Comma-separated languages. First entry is the primary.
                    Supported: go, python, typescript, javascript
  --minimal         Install hooks + settings + rules only (no CLAUDE.md).
                    Fill the stack later with /yds-setup in Claude Code.

Options:
  --target DIR      Target project directory (default: current directory)
  --name NAME       Project name for CLAUDE.md (default: target dir name)
  --branch NAME     Default branch (default: main)
  --pm PM           Node package manager: pnpm | npm | yarn | bun (default: pnpm)
  --python-pm PM    Python package manager: uv | pip | poetry (default: uv)
  --guard-pip       Enable the "use uv, not pip install" bash guard
  --no-ci           Skip GitHub Actions CI / security-scan generation
  --no-format-hook  Skip the format-on-write hook
  --no-bash-guard   Skip the dangerous-bash guard hook
  --no-guidance-hooks  Skip the SessionStart / Stop guidance hooks
  --no-rules        Skip .claude/rules/dev-skills-cycle.md
  --no-env-guard    Skip .gitignore/.env.example handling
  --protect         Apply branch protection (required status checks) via gh CLI
  --with-skills     Also run: npx skills add ymd38/dev-skills --skill '*' --agent claude-code -y --copy
  --force           Overwrite existing files (default: keep existing)
  -h, --help        Show this help

With --langs, GitHub Actions workflows (ci.yml, security-scan.yml) and
.gitleaks.toml / .semgrepignore are generated by default; --minimal and
--no-ci skip them. Generated checks only gate merges once branch protection
marks them required — pass --protect (needs gh auth + admin) or configure it
in GitHub settings; the final checklist reports the current state.
EOF
}

# ── Args ─────────────────────────────────────
TARGET="$PWD"
LANGS=""
MINIMAL=0
NAME=""
BRANCH="main"
PM="pnpm"
PY_PM="uv"
GUARD_PIP=0
NO_CI=0
NO_FORMAT_HOOK=0
NO_BASH_GUARD=0
NO_GUIDANCE_HOOKS=0
NO_RULES=0
NO_ENV_GUARD=0
PROTECT=0
WITH_SKILLS=0
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)     TARGET="$2"; shift 2 ;;
    --langs)      LANGS="$2"; shift 2 ;;
    --minimal)    MINIMAL=1; shift ;;
    --name)       NAME="$2"; shift 2 ;;
    --branch)     BRANCH="$2"; shift 2 ;;
    --pm)         PM="$2"; shift 2 ;;
    --python-pm)  PY_PM="$2"; shift 2 ;;
    --guard-pip)  GUARD_PIP=1; shift ;;
    --no-ci)      NO_CI=1; shift ;;
    --no-format-hook)    NO_FORMAT_HOOK=1; shift ;;
    --no-bash-guard)     NO_BASH_GUARD=1; shift ;;
    --no-guidance-hooks) NO_GUIDANCE_HOOKS=1; shift ;;
    --no-rules)          NO_RULES=1; shift ;;
    --no-env-guard)      NO_ENV_GUARD=1; shift ;;
    --protect)           PROTECT=1; shift ;;
    --with-skills) WITH_SKILLS=1; shift ;;
    --force)      FORCE=1; shift ;;
    -h|--help)    usage; exit 0 ;;
    *) echo "error: unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ -z "$LANGS" && "$MINIMAL" != "1" ]]; then
  echo "error: --langs is required (e.g. --langs go,typescript), or pass --minimal" >&2
  usage >&2
  exit 1
fi

TARGET="$(cd "$TARGET" && pwd)"
[[ -z "$NAME" ]] && NAME="$(basename "$TARGET")"

IFS=',' read -r -a LANG_ARR <<<"$LANGS"
for l in "${LANG_ARR[@]:-}"; do
  case "$l" in
    go|python|typescript|javascript|"") ;;
    *) echo "error: unsupported language: $l (supported: go, python, typescript, javascript)" >&2; exit 1 ;;
  esac
done

case "$PM" in pnpm|npm|yarn|bun) ;; *) echo "error: unsupported --pm: $PM" >&2; exit 1 ;; esac
case "$PY_PM" in uv|pip|poetry) ;; *) echo "error: unsupported --python-pm: $PY_PM" >&2; exit 1 ;; esac

echo "==> dev-skills harness → $TARGET"

# ── Status trackers for the final checklist ──
ST_HOOKS=""
ST_SETTINGS=""
ST_CLAUDE=""
ST_RULES=""
ST_CI=""
ST_ENV=""
ST_SKILLS="skipped (use --with-skills or: npx skills add ymd38/dev-skills --skill '*' --agent claude-code -y --copy)"

mkdir -p "$TARGET/.claude/hooks" "$TARGET/.claude/rules"

# ── Hooks (per-component selection) ──────────
HOOK_FILES=()
DROPPED_HOOKS=""
if [[ "$NO_FORMAT_HOOK" == "1" ]]; then DROPPED_HOOKS="${DROPPED_HOOKS:+$DROPPED_HOOKS,}post-write-format.sh"; else HOOK_FILES+=(post-write-format.sh); fi
if [[ "$NO_BASH_GUARD" == "1" ]]; then DROPPED_HOOKS="${DROPPED_HOOKS:+$DROPPED_HOOKS,}pre-bash-guard.sh"; else HOOK_FILES+=(pre-bash-guard.sh); fi
if [[ "$NO_GUIDANCE_HOOKS" == "1" ]]; then
  DROPPED_HOOKS="${DROPPED_HOOKS:+$DROPPED_HOOKS,}stop-suggest-cycle.sh,session-start-context.sh"
else
  HOOK_FILES+=(stop-suggest-cycle.sh session-start-context.sh)
fi

installed=0 kept=0
for f in "${HOOK_FILES[@]:-}"; do
  [[ -z "$f" ]] && continue
  src="$TEMPLATES/hooks/$f"
  dst="$TARGET/.claude/hooks/$f"
  if [[ -f "$dst" && "$FORCE" != "1" ]]; then
    kept=$((kept + 1))
  else
    cp "$src" "$dst"
    chmod +x "$dst"
    installed=$((installed + 1))
  fi
done
ST_HOOKS="installed=$installed kept=$kept${DROPPED_HOOKS:+ (skipped: $DROPPED_HOOKS)}"

# ── settings.json (create or merge hooks) ────
# The settings template must only register the hooks actually installed.
SETTINGS="$TARGET/.claude/settings.json"
SETTINGS_SRC="$TEMPLATES/settings.json.template"
if [[ -n "$DROPPED_HOOKS" ]]; then
  if command -v jq >/dev/null 2>&1; then
    SETTINGS_SRC="$(mktemp)"
    jq --arg drop "$DROPPED_HOOKS" '
      ($drop | split(",") | map(select(length > 0))) as $d
      | .hooks |= (with_entries(
          .value |= map(select(
            ((.hooks[0].command) // "") as $c
            | (($d | any(. as $n | $c | contains($n))) | not)
          ))
        ) | with_entries(select((.value | length) > 0)))
    ' "$TEMPLATES/settings.json.template" >"$SETTINGS_SRC"
  else
    echo "warn: jq unavailable — settings.json will still reference skipped hooks; remove those entries manually" >&2
  fi
fi
if [[ ! -f "$SETTINGS" || "$FORCE" == "1" ]]; then
  cp "$SETTINGS_SRC" "$SETTINGS"
  ST_SETTINGS="created"
elif command -v jq >/dev/null 2>&1; then
  tmp="$(mktemp)"
  jq -s '
    (.[0].hooks // {}) as $cur | (.[1].hooks // {}) as $tpl |
    .[0] + {hooks: (
      ($cur | to_entries) + ($tpl | to_entries)
      | group_by(.key)
      | map({key: .[0].key, value: (map(.value) | add | unique_by(tostring))})
      | from_entries
    )}
  ' "$SETTINGS" "$SETTINGS_SRC" >"$tmp"
  mv "$tmp" "$SETTINGS"
  ST_SETTINGS="merged (existing hooks preserved)"
else
  ST_SETTINGS="SKIPPED — exists and jq unavailable; merge the hooks block from templates/settings.json.template manually"
fi

# Enable the pip guard via settings env when requested
if [[ "$GUARD_PIP" == "1" ]]; then
  if command -v jq >/dev/null 2>&1; then
    tmp="$(mktemp)"
    jq '.env = ((.env // {}) + {DEV_SKILLS_GUARD_PIP: "1"})' "$SETTINGS" >"$tmp"
    mv "$tmp" "$SETTINGS"
    ST_SETTINGS="$ST_SETTINGS + pip guard enabled"
  else
    echo "warn: --guard-pip needs jq to edit settings.json; add {\"env\":{\"DEV_SKILLS_GUARD_PIP\":\"1\"}} manually" >&2
  fi
fi

# ── Rules ────────────────────────────────────
RULES="$TARGET/.claude/rules/dev-skills-cycle.md"
if [[ "$NO_RULES" == "1" ]]; then
  ST_RULES="skipped (--no-rules)"
elif [[ -f "$RULES" && "$FORCE" != "1" ]]; then
  ST_RULES="kept existing"
else
  cp "$TEMPLATES/rules/dev-skills-cycle.md" "$RULES"
  ST_RULES="installed"
fi

# ── CLAUDE.md ────────────────────────────────
node_block() { # $1: TypeScript|JavaScript
  local lang="$1" run exec_cmd
  case "$PM" in
    pnpm) run="pnpm" exec_cmd="pnpm exec" ;;
    npm)  run="npm"  exec_cmd="npx" ;;
    yarn) run="yarn" exec_cmd="yarn" ;;
    bun)  run="bun"  exec_cmd="bunx" ;;
  esac
  printf '### %s (%s)\n' "$lang" "$PM"
  printf -- '- Install: `%s install`\n' "$run"
  printf -- '- Test: `%s test`\n' "$run"
  printf -- '- Lint: `%s run lint`\n' "$run"
  [[ "$lang" == "TypeScript" ]] && printf -- '- Typecheck: `%s tsc --noEmit`\n' "$exec_cmd"
  printf -- '- Format: Prettier (hook on Write/Edit)\n'
}

python_block() {
  printf '### Python (%s)\n' "$PY_PM"
  case "$PY_PM" in
    uv)
      printf -- '- Install: `uv sync`\n- Test: `uv run pytest`\n- Lint / Format: `uv run ruff check` / `uv run ruff format` (format hook on Write/Edit)\n' ;;
    pip)
      printf -- '- Install: `pip install -e .`\n- Test: `pytest`\n- Lint / Format: `ruff check` / `ruff format` (format hook on Write/Edit)\n' ;;
    poetry)
      printf -- '- Install: `poetry install`\n- Test: `poetry run pytest`\n- Lint / Format: `poetry run ruff check` / `poetry run ruff format` (format hook on Write/Edit)\n' ;;
  esac
}

go_block() {
  printf '### Go\n- Install: `go mod download`\n- Test: `go test ./...`\n- Lint: `golangci-lint run` (fallback: `go vet ./...`)\n- Format: goimports / gofmt (hook on Write/Edit)\n'
}

lang_title() {
  case "$1" in
    go) echo "Go" ;;
    python) echo "Python" ;;
    typescript) echo "TypeScript" ;;
    javascript) echo "JavaScript" ;;
  esac
}

CLAUDE_MD="$TARGET/CLAUDE.md"
if [[ "$MINIMAL" == "1" ]]; then
  ST_CLAUDE="skipped (--minimal) — run /yds-setup in Claude Code to fill the stack"
elif [[ -f "$CLAUDE_MD" && "$FORCE" != "1" ]]; then
  ST_CLAUDE="kept existing — run /yds-setup in Claude Code to merge the cycle section"
else
  primary="$(lang_title "${LANG_ARR[0]}")"
  others=""
  if [[ ${#LANG_ARR[@]} -gt 1 ]]; then
    for l in "${LANG_ARR[@]:1}"; do
      t="$(lang_title "$l")"
      others="${others:+$others, }$t"
    done
  fi
  STACK_BLOCKS="Primary: $primary"
  [[ -n "$others" ]] && STACK_BLOCKS+=$'\n'"Also present: $others"
  STACK_BLOCKS+=$'\n'
  for l in "${LANG_ARR[@]}"; do
    STACK_BLOCKS+=$'\n'
    case "$l" in
      go)         STACK_BLOCKS+="$(go_block)" ;;
      python)     STACK_BLOCKS+="$(python_block)" ;;
      typescript) STACK_BLOCKS+="$(node_block TypeScript)" ;;
      javascript) STACK_BLOCKS+="$(node_block JavaScript)" ;;
    esac
    STACK_BLOCKS+=$'\n'
  done

  {
    while IFS= read -r line; do
      if [[ "$line" == "{{STACK_BLOCKS}}" ]]; then
        printf '%s\n' "$STACK_BLOCKS"
      else
        line=${line//\{\{PROJECT_NAME\}\}/$NAME}
        line=${line//\{\{DEFAULT_BRANCH\}\}/$BRANCH}
        printf '%s\n' "$line"
      fi
    done <"$TEMPLATES/CLAUDE.md.template"
  } >"$CLAUDE_MD"
  ST_CLAUDE="created ($primary${others:+ + $others})"
fi

# ── GitHub Actions CI + security scan ────────
has_lang() {
  local l
  for l in "${LANG_ARR[@]:-}"; do [[ "$l" == "$1" ]] && return 0; done
  return 1
}

go_ci_job() {
  cat <<'EOF'
  go:
    name: Go (build, test, lint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code go.mod
          if [ -f go.sum ]; then git diff --exit-code go.sum; fi
      - name: Build
        run: go build ./...
      - name: Test (race)
        run: go test ./... -race
      - name: Lint
        # Supply chain: pin the version (never @latest).
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
          golangci-lint run --timeout=5m
EOF
}

node_ci_job() {
  echo "  node:"
  echo "    name: Node (lint, typecheck, test)"
  echo "    runs-on: ubuntu-latest"
  echo "    steps:"
  echo "      - uses: actions/checkout@v4"
  case "$PM" in
    pnpm)
      cat <<'EOF'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # Strict by design (shift-left): a missing lint/typecheck/test script
      # fails the job. Add the scripts before the first code PR.
      - name: Lint
        run: pnpm run lint
      - name: Typecheck
        run: pnpm run typecheck
      - name: Test
        run: pnpm run test
EOF
      ;;
    npm)
      cat <<'EOF'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Install dependencies
        run: npm ci
      # Strict by design (shift-left): a missing lint/typecheck/test script
      # fails the job. Add the scripts before the first code PR.
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Test
        run: npm run test
EOF
      ;;
    yarn)
      cat <<'EOF'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # Strict by design (shift-left): a missing lint/typecheck/test script
      # fails the job. Add the scripts before the first code PR.
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test
EOF
      ;;
    bun)
      cat <<'EOF'
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      # Strict by design (shift-left): a missing lint/typecheck/test script
      # fails the job. Add the scripts before the first code PR.
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run typecheck
      - name: Test
        run: bun run test
EOF
      ;;
  esac
}

python_ci_job() {
  echo "  python:"
  echo "    name: Python (lint, test)"
  echo "    runs-on: ubuntu-latest"
  echo "    steps:"
  echo "      - uses: actions/checkout@v4"
  case "$PY_PM" in
    uv)
      cat <<'EOF'
      - uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
      - name: Lint (ruff)
        run: |
          uv run ruff check .
          uv run ruff format --check .
      - name: Test
        # Strict by design (shift-left): "no tests collected" (exit 5) fails
        # the job. Land the first test with the first code PR.
        run: uv run pytest -q
EOF
      ;;
    pip)
      cat <<'EOF'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -e .
          pip install ruff pytest
      - name: Lint (ruff)
        run: |
          ruff check .
          ruff format --check .
      - name: Test
        # Strict by design (shift-left): "no tests collected" (exit 5) fails
        # the job. Land the first test with the first code PR.
        run: pytest -q
EOF
      ;;
    poetry)
      cat <<'EOF'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install
      - name: Lint (ruff)
        run: |
          poetry run ruff check .
          poetry run ruff format --check .
      - name: Test
        # Strict by design (shift-left): "no tests collected" (exit 5) fails
        # the job. Land the first test with the first code PR.
        run: poetry run pytest -q
EOF
      ;;
  esac
}

HAS_NODE=0
NODE_AUDIT_JOB=""
CI_GENERATED=0
if [[ "$MINIMAL" == "1" ]]; then
  ST_CI="skipped (--minimal; CI needs languages — re-run with --langs or use /yds-setup)"
elif [[ "$NO_CI" == "1" ]]; then
  ST_CI="skipped (--no-ci)"
else
  CI_GENERATED=1
  mkdir -p "$TARGET/.github/workflows"

  # Assemble language-dependent fragments
  CI_PATHS=""
  CI_JOBS=""
  SEMGREP_CONFIGS=""
  HAS_NODE=0
  if has_lang go; then
    CI_PATHS+="      - '**/*.go'"$'\n'"      - 'go.mod'"$'\n'"      - 'go.sum'"$'\n'
    CI_JOBS+="$(go_ci_job)"$'\n\n'
    SEMGREP_CONFIGS+="            --config p/golang \\"$'\n'
  fi
  if has_lang python; then
    CI_PATHS+="      - '**/*.py'"$'\n'"      - 'pyproject.toml'"$'\n'
    CI_JOBS+="$(python_ci_job)"$'\n\n'
    SEMGREP_CONFIGS+="            --config p/python \\"$'\n'
  fi
  if has_lang typescript || has_lang javascript; then
    HAS_NODE=1
    CI_PATHS+="      - '**/*.ts'"$'\n'"      - '**/*.tsx'"$'\n'"      - '**/*.js'"$'\n'"      - '**/*.vue'"$'\n'"      - 'package.json'"$'\n'
    CI_JOBS+="$(node_ci_job)"$'\n\n'
    has_lang typescript && SEMGREP_CONFIGS+="            --config p/typescript \\"$'\n'
    has_lang javascript && SEMGREP_CONFIGS+="            --config p/javascript \\"$'\n'
  fi

  NODE_AUDIT_JOB=""
  if [[ "$HAS_NODE" == "1" && ( "$PM" == "pnpm" || "$PM" == "npm" ) ]]; then
    NODE_AUDIT_JOB=$'\n'"  dep-audit-node:"$'\n'
    NODE_AUDIT_JOB+="    name: Node Dependency Audit"$'\n'
    NODE_AUDIT_JOB+="    runs-on: ubuntu-latest"$'\n'
    NODE_AUDIT_JOB+="    steps:"$'\n'
    NODE_AUDIT_JOB+="      - uses: actions/checkout@v4"$'\n'
    if [[ "$PM" == "pnpm" ]]; then
      NODE_AUDIT_JOB+="      - uses: pnpm/action-setup@v4"$'\n'
      NODE_AUDIT_JOB+="        with:"$'\n'
      NODE_AUDIT_JOB+="          version: 10"$'\n'
      NODE_AUDIT_JOB+="      - uses: actions/setup-node@v4"$'\n'
      NODE_AUDIT_JOB+="        with:"$'\n'
      NODE_AUDIT_JOB+="          node-version: '22'"$'\n'
      NODE_AUDIT_JOB+="          cache: pnpm"$'\n'
      NODE_AUDIT_JOB+="      - name: Install dependencies"$'\n'
      NODE_AUDIT_JOB+="        run: pnpm install --frozen-lockfile"$'\n'
      NODE_AUDIT_JOB+="      - name: Audit production dependencies"$'\n'
      NODE_AUDIT_JOB+="        # devDependencies do not ship to production"$'\n'
      NODE_AUDIT_JOB+="        run: pnpm audit --prod --audit-level=high"
    else
      NODE_AUDIT_JOB+="      - uses: actions/setup-node@v4"$'\n'
      NODE_AUDIT_JOB+="        with:"$'\n'
      NODE_AUDIT_JOB+="          node-version: '22'"$'\n'
      NODE_AUDIT_JOB+="          cache: npm"$'\n'
      NODE_AUDIT_JOB+="      - name: Install dependencies"$'\n'
      NODE_AUDIT_JOB+="        run: npm ci"$'\n'
      NODE_AUDIT_JOB+="      - name: Audit production dependencies"$'\n'
      NODE_AUDIT_JOB+="        # devDependencies do not ship to production"$'\n'
      NODE_AUDIT_JOB+="        run: npm audit --omit=dev --audit-level=high"
    fi
  fi

  render_workflow() { # $1: template, $2: destination
    local line
    while IFS= read -r line; do
      case "$line" in
        "{{CI_PATHS}}")             printf '%s' "$CI_PATHS" ;;
        "{{CI_JOBS}}")              printf '%s' "$CI_JOBS" ;;
        "{{SEMGREP_LANG_CONFIGS}}") printf '%s' "$SEMGREP_CONFIGS" ;;
        "{{NODE_AUDIT_JOB}}")       [[ -n "$NODE_AUDIT_JOB" ]] && printf '%s\n' "$NODE_AUDIT_JOB" ;;
        *)
          line=${line//\{\{DEFAULT_BRANCH\}\}/$BRANCH}
          printf '%s\n' "$line"
          ;;
      esac
    done <"$1" >"$2"
  }

  ci_written=0 ci_kept=0
  if [[ -f "$TARGET/.github/workflows/ci.yml" && "$FORCE" != "1" ]]; then
    ci_kept=$((ci_kept + 1))
  else
    render_workflow "$TEMPLATES/github/ci.yml" "$TARGET/.github/workflows/ci.yml"
    ci_written=$((ci_written + 1))
  fi
  if [[ -f "$TARGET/.github/workflows/security-scan.yml" && "$FORCE" != "1" ]]; then
    ci_kept=$((ci_kept + 1))
  else
    render_workflow "$TEMPLATES/github/security-scan.yml" "$TARGET/.github/workflows/security-scan.yml"
    ci_written=$((ci_written + 1))
  fi
  if [[ -f "$TARGET/.gitleaks.toml" && "$FORCE" != "1" ]]; then
    ci_kept=$((ci_kept + 1))
  else
    cp "$TEMPLATES/github/gitleaks.toml" "$TARGET/.gitleaks.toml"
    ci_written=$((ci_written + 1))
  fi
  if [[ -f "$TARGET/.semgrepignore" && "$FORCE" != "1" ]]; then
    ci_kept=$((ci_kept + 1))
  else
    cp "$TEMPLATES/github/semgrepignore" "$TARGET/.semgrepignore"
    ci_written=$((ci_written + 1))
  fi
  ST_CI="written=$ci_written kept=$ci_kept (ci.yml, security-scan.yml, .gitleaks.toml, .semgrepignore)"
fi

# ── .env guard ───────────────────────────────
if [[ "$NO_ENV_GUARD" == "1" ]]; then
  ST_ENV="skipped (--no-env-guard)"
else
env_notes=""
if [[ ! -f "$TARGET/.gitignore" ]]; then
  printf '.env\n.env.*\n!.env.example\n' >"$TARGET/.gitignore"
  env_notes=".gitignore created"
else
  added=0
  for pat in '.env' '.env.*' '!.env.example'; do
    grep -qxF "$pat" "$TARGET/.gitignore" || { printf '%s\n' "$pat" >>"$TARGET/.gitignore"; added=$((added + 1)); }
  done
  env_notes=".gitignore +$added lines"
fi
if [[ ! -f "$TARGET/.env.example" ]]; then
  printf '# Mirror every key used in .env here with a safe placeholder value.\n# Real credentials live only in .env (gitignored).\n' >"$TARGET/.env.example"
  env_notes="$env_notes, .env.example created"
fi
ST_ENV="$env_notes"
fi

# ── Skills ───────────────────────────────────
if [[ "$WITH_SKILLS" == "1" ]]; then
  if command -v npx >/dev/null 2>&1; then
    if (cd "$TARGET" && npx --yes skills add ymd38/dev-skills --skill '*' --agent claude-code -y --copy); then
      ST_SKILLS="installed via npx skills add"
    else
      ST_SKILLS="FAILED — run manually: npx skills add ymd38/dev-skills --skill '*' --agent claude-code -y --copy"
    fi
  else
    ST_SKILLS="SKIPPED — npx not found; run manually: npx skills add ymd38/dev-skills --skill '*' --agent claude-code -y --copy"
  fi
fi

# ── Branch protection (required status checks) ──
# A CI check only gates merges once branch protection marks it required.
ST_PROTECT="skipped (no CI generated)"
if [[ "$CI_GENERATED" == "1" ]]; then
  if ! command -v gh >/dev/null 2>&1; then
    ST_PROTECT="unknown (gh CLI not found — set required checks in GitHub settings)"
  elif ! git -C "$TARGET" remote get-url origin >/dev/null 2>&1; then
    ST_PROTECT="NOT CONFIGURED (no git remote yet — after the first push, re-run with --protect)"
  else
    repo_slug="$(cd "$TARGET" && gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
    if [[ -z "$repo_slug" ]]; then
      ST_PROTECT="unknown (gh cannot resolve the repository — check gh auth status)"
    elif [[ "$PROTECT" == "1" ]]; then
      contexts=""
      has_lang go && contexts="${contexts:+$contexts,}\"Go (build, test, lint)\""
      [[ "$HAS_NODE" == "1" ]] && contexts="${contexts:+$contexts,}\"Node (lint, typecheck, test)\""
      has_lang python && contexts="${contexts:+$contexts,}\"Python (lint, test)\""
      contexts="${contexts:+$contexts,}\"Secret Scan (Gitleaks)\",\"SAST (Semgrep)\""
      [[ -n "$NODE_AUDIT_JOB" ]] && contexts="$contexts,\"Node Dependency Audit\""
      payload="$(mktemp)"
      printf '{"required_status_checks":{"strict":true,"contexts":[%s]},"enforce_admins":true,"required_pull_request_reviews":null,"restrictions":null,"allow_force_pushes":false,"allow_deletions":false}\n' "$contexts" >"$payload"
      if (cd "$TARGET" && gh api -X PUT "repos/$repo_slug/branches/$BRANCH/protection" --input "$payload" >/dev/null 2>&1); then
        ST_PROTECT="applied (required checks incl. Gitleaks / Semgrep on $BRANCH)"
      else
        ST_PROTECT="FAILED — branch protection requires REPOSITORY ADMIN. Verify: (1) gh auth status shows an account with admin on this repo (a 403 means the token lacks admin), (2) the $BRANCH branch is pushed. Then re-run with --protect, or set required checks manually in GitHub settings"
      fi
      rm -f "$payload"
    else
      if (cd "$TARGET" && gh api "repos/$repo_slug/branches/$BRANCH/protection" >/dev/null 2>&1); then
        ST_PROTECT="configured on $BRANCH"
      else
        ST_PROTECT="NOT CONFIGURED — re-run with --protect, or set required checks in GitHub settings"
      fi
    fi
  fi
fi

# ── Checklist ────────────────────────────────
cat <<EOF

[dev-skills harness]
  target:     $TARGET
  hooks:      $ST_HOOKS
  settings:   $ST_SETTINGS
  rules:      $ST_RULES
  CLAUDE.md:  $ST_CLAUDE
  CI:         $ST_CI
  protection: $ST_PROTECT
  env guard:  $ST_ENV
  skills:     $ST_SKILLS
  next:       open the project in Claude Code, then try "/yds-software-evaluation ." — or "/yds-setup" to refine commands interactively
EOF
